2023-09-22 12:09:14,136 INFO    MainThread:4354 [wandb_setup.py:_flush():76] Loading settings from /home/lmur/.config/wandb/settings
2023-09-22 12:09:14,137 INFO    MainThread:4354 [wandb_setup.py:_flush():76] Loading settings from /home/lmur/hum_obj_int/stillfast/wandb/settings
2023-09-22 12:09:14,137 INFO    MainThread:4354 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-09-22 12:09:14,137 INFO    MainThread:4354 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': 'main.py'}
2023-09-22 12:09:14,137 INFO    MainThread:4354 [wandb_init.py:_log_setup():428] Logging user logs to ./output/sta/StillFast_baseline_0/version_0/wandb/run-20230922_120914-1qzblrtk/logs/debug.log
2023-09-22 12:09:14,137 INFO    MainThread:4354 [wandb_init.py:_log_setup():429] Logging internal logs to ./output/sta/StillFast_baseline_0/version_0/wandb/run-20230922_120914-1qzblrtk/logs/debug-internal.log
2023-09-22 12:09:14,137 INFO    MainThread:4354 [wandb_init.py:init():462] calling init triggers
2023-09-22 12:09:14,138 INFO    MainThread:4354 [wandb_init.py:init():466] wandb.init called with sweep_config: {}
config: {}
2023-09-22 12:09:14,138 INFO    MainThread:4354 [wandb_init.py:init():515] starting backend
2023-09-22 12:09:14,138 INFO    MainThread:4354 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-09-22 12:09:14,166 INFO    MainThread:4354 [backend.py:ensure_launched():217] starting backend process...
2023-09-22 12:09:14,192 INFO    MainThread:4354 [backend.py:ensure_launched():222] started backend process with pid: 4642
2023-09-22 12:09:14,195 INFO    MainThread:4354 [wandb_init.py:init():525] backend started and connected
2023-09-22 12:09:14,212 INFO    MainThread:4354 [wandb_init.py:init():596] updated telemetry
2023-09-22 12:09:14,257 INFO    MainThread:4354 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2023-09-22 12:09:44,259 INFO    MainThread:4354 [interface_shared.py:_communicate_run():326] couldn't get run from backend
2023-09-22 12:09:44,259 ERROR   MainThread:4354 [wandb_init.py:init():636] backend process timed out
2023-09-22 12:09:44,260 ERROR   MainThread:4354 [wandb_init.py:init():647] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-09-22 12:09:44,281 ERROR   MainThread:4354 [wandb_init.py:init():1026] error
Traceback (most recent call last):
  File "/home/lmur/miniconda3/envs/stillfast/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 999, in init
    run = wi.init()
  File "/home/lmur/miniconda3/envs/stillfast/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 651, in init
    backend.cleanup()
  File "/home/lmur/miniconda3/envs/stillfast/lib/python3.7/site-packages/wandb/sdk/backend/backend.py", line 246, in cleanup
    self.interface.join()
  File "/home/lmur/miniconda3/envs/stillfast/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 475, in join
    super().join()
  File "/home/lmur/miniconda3/envs/stillfast/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 666, in join
    _ = self._communicate_shutdown()
  File "/home/lmur/miniconda3/envs/stillfast/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 472, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/lmur/miniconda3/envs/stillfast/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/lmur/miniconda3/envs/stillfast/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
